version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ="America/Los_Angeles"
      - ADVERTISE_IP="https://192.168.1.110:32400/"
      - ALLOWED_NETWORKS="192.168.1.0/24,172.16.0.0/16"
    labels:
      - "container_name=plex"
    hostname: cronos
    volumes:
      - /docker/plex:/config
      - /data/media:/data
