---
- hosts: localhost
  connection: local
  vars_files:
    - './vars/main.yml'

  tasks:
    - name: Pull plex image
      docker_image:
        name: "{{ image_name }}"
        rm: true

    - name: Start plex container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        restart: true
        restart_policy: unless-stopped
				hostname: "{{ hostname }}"
				labels:
					container_name: plex
        ports:
     			- 32400:32400/tcp
      		- 3005:3005/tcp
      		- 8324:8324/tcp
      		- 32469:32469/tcp
      		- 1900:1900/udp
      		- 32410:32410/udp
      		- 32412:32412/udp
      		- 32413:32413/udp
      		- 32414:32414/udp
				volumes:
					- /docker/plex:/config
					- /data/media:/data
				env:
					TZ: "America_Los_Angeles"
					ADVERTISE_IP: "https://{{ advertise_ip }}:32400/"
					ALLOWED_NETWORKS: "{{ allowed_networks }}"
